---
title: "Notebook"
author: "me"
date: "14/05/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Allometry Project

>How does plant weight scale with height?

- No relationship
- Linear
- To the third power
- To the second power

## Load our data

```{r}

seeds <- read.csv("https://raw.githubusercontent.com/jmadin/himbr/master/data/seed_root_herbivores.csv", as.is=TRUE)
head(seeds)
summary(seeds)

list(12, "tree", c(FALSE, TRUE, FALSE))


```


## A function for standard error

```{r}
standard_error<-function(x) {sd(x)/sqrt(lenght(x))
  return(se)}
  
```

## Seed Weight-Height Plot

```{r}
plot(seeds$Height, seeds$Weight)
plot(Weight~Height, data=seeds)

seeds$Weight_log10<-log10(seeds$Weight)
seeds$Height_log10<-log10(seeds$Height)

plot(Weight_log10~Height_log10, data=seeds)

plot(Weight_log10~Height_log10, data=seeds, col="red", xlab="Height, log10", main="My big fig")

par(mfrow=c(2,2))

plot(Weight_log10~Height_log10, data=seeds, col="red", xlab="Height, log10", main="My big fig")

plot(Weight_log10~Height_log10, data=seeds, col="red", xlab="Height, log10", main="My big fig")

plot(Weight_log10~Height_log10, data=seeds, col="red", xlab="Height, log10", main="My big fig")

plot(Weight_log10~Height_log10, data=seeds, col="red", xlab="Height, log10", main="My big fig")
```

## Data Analysis

```{r}
mod<-lm(Weight_log10~Height_log10, data=seeds)
summary(mod)
mod$coef
write.csv(mod$coef, "output/model_coefs.csv")
```

## Figure

```{r}

h<-sort(seeds$Height_log10)
pred<-predict(mod,list(Height_log10=h),interval="confidence")

pdf("figs/figure_1.pdf")

plot(Weight_log10~Height_log10, data=seeds, col="red", xlab="Height, log10", main="My big fig")
lines(h, pred[,1], col="black", lty=2)
polygon(c(h,rev(h)),c(pred[,2],rev(pred[,3])),col=rgb(0,0,0,0.2),border=NA)

dev.off()

```

##Conclusions

The slope of the relationship between height and weight is `r round(mod$coef[2],2)`

